{% set name = "vharfbuzz" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vharfbuzz-{{ version }}.tar.gz
  sha256: cc5570f0dc61edc449364fd2ec3dee88819284132267f25eb92757e2137de247

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fonttools
    - python >={{ python_min }}
    - uharfbuzz

test:
  imports:
    - vharfbuzz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simoncozens/vharfbuzz
  summary: A user-friendlier way to use Harfbuzz in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
