{% set name = "vharfbuzz" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vharfbuzz-{{ version }}.tar.gz
  sha256: b835f67d8ab1578c2600020c7c0ddd0688569aad4dd15bab4931053a3491a666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fonttools
    - python >=3.6
    - uharfbuzz

test:
  imports:
    - vharfbuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simoncozens/vharfbuzz
  summary: A user-friendlier way to use Harfbuzz in Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
